#!/usr/bin/env python
"""
mkdirectories is a tool to create the necessary directory strucuture
for reducing the F2 long slit data for the GS-2013B-Q-73 project.
"""

import argparse
from bookkeeping import mkdirectories

VERSION = '1.0.1'

def parse_args():
    """
    Parse command line arguments.
    """
    parser = argparse.ArgumentParser(
					description='Create DR directory structure')
    parser.add_argument('programID', type=str, help='Program ID')
    parser.add_argument('targetname', type=str, help='Target name')
    parser.add_argument('obsdate', type=str, 
						help='YYYYMMDD Date of observation')
    parser.add_argument('reduxdate', type=str, 
						help='DDMonYYYY Date of reduction')
    parser.add_argument('bands', type=str, nargs='+', help='Bands')
    
    parser.add_argument('-v', '--verbose', dest='verbose', 
					action='store_true', default=False, 
					help='Toggle on verbose mode')
    parser.add_argument('--debug', dest='debug', action='store_true', 
					default=False, help='Toggle on debug mode')
        
    if parser.parse_args().debug:
        print parser.parse_args()

    return parser.parse_args()
    
if __name__ == '__main__':
    ARGS = parse_args()
    mkdirectories(ARGS.programID, ARGS.targetname, 
        ARGS.obsdate, ARGS.reduxdate, ARGS.bands)