#!/usr/bin/env python

import argparse
from bookkeeping import mkdirectories

VERSION = '1.0.0'

def parse_args():
	"""
	Parse command line arguments.
	"""
	p = argparse.ArgumentParser(description='Create DR directory structure')
	p.add_argument('programID', type=str, nargs=1, help='Program ID')
	p.add_argument('targetname', type=str, nargs=1, help='Target name')
	p.add_argument('obsdate', type=str, nargs=1, help='YYYYMMDD Date of observation')
	p.add_argument('reduxdate', type=str, nargs=1, help='DDMonYYYY Date of reduction')
	p.add_argument('bands', type=str, nargs='+', help='Bands')
	
	p.add_argument('-v', '--verbose', dest='verbose', action='store_true', default=False, help='Toggle on verbose mode')
	p.add_argument('--debug', dest='debug', action='store_true', default=False, help='Toggle on debug mode')
	
	args = p.parse_args()

	# Get the positional arguments out of a list
	args.programID = args.programID[0]
	args.targetname = args.targetname[0]
	args.obsdate = args.obsdate[0]
	args.reduxdate = args.reduxdate[0]
	
	if args.debug:
		print args
	
	
	
	return args
	
if __name__ == '__main__':
	args = parse_args()
	mkdirectories(args.programID, args.targetname, 
		args.obsdate, args.reduxdate, args.bands)