#!/usr/bin/env python

import argparse
from specplot import specplot
from astrodata import AstroData
import matplotlib.pyplot as plt

VERSION = '0.1.0'

def parse_args():
	"""
	Parse command line arguments for splot
	"""
	p = argparse.ArgumentParser(description='Plot a 1-D spectrum')
	p.add_argument('spectrum', type=str, nargs=1, 
					help='File name of spectrum to plot')
	p.add_argument('-x', '--extension', dest='extension', type=str, 
					action='store', default='1', 
					help='Extension of the science spectrum')
	p.add_argument('-t', '--title', dest='title', type=str, action='store',
					default='', help='Title for the plot')
	p.add_argument('-l', '--linelist', dest='linelist', type=str, 
					action='store', default=None, 
					help='Name of the line list to use for annotation')
	p.add_argument('-z', '--redshift', dest='redshift', type=float,
					action='store', default=0.,
					help='Redshift to apply to the line list')
	p.add_argument('-y', '--ylim', dest='ylim', nargs=2, type=float,
					action='store', default=None, 
					help='Y-axis lower and upper limit')
	p.add_argument('-o', dest='output', type=str, action='store',
					default=None, help='Name of the png output.')
	
	p.add_argument('-v', '--verbose', dest='verbose', action='store_true',
				default=False, help='Toggle on verbose mode')
	p.add_argument('--debug', action='store_true', default=False,
				help='Toggle on debug mode')
	
	args = p.parse_args()
	
	if args.debug:
		print args
	
	ext = args.extension.split(',')
	if ext[0].isdigit():
		args.extension = int(ext[0])
	else:
		args.extension = (ext[0].upper(), int(ext[1]))
	
	if args.debug:
		print args.extension
	
	return args

if __name__ == '__main__':
	args = parse_args()
	
	ad = AstroData(args.spectrum[0])
	specplot(ad.hdulist, args.extension, title=args.title,
			line_list_name=args.linelist, redshift=args.redshift,
			ylimits=args.ylim, output_plot_name=args.output)
	plt.show(block=True)
